### ISSUE TITLE
web service non-graceful crash on trivial bad user input

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_runner#10]
The CQL Runner web service at http://cql-runner.dataphoria.org crashes on trivial bad user input rather than handling this gracefully.

The simplest reproduction is to just go to http://cql-runner.dataphoria.org and hit the "Run" button while the Input field has its default value consisting of a comment and no code; alternately the Input pane can be completely blank for contain garbage like just the character "x".

The actual result in the Output pane is the error message:  ```>> Engine Service call failed: Response with status: 500 Request failed. for URL: http://cql.dataphoria.org/cql/evaluate```

Now an HTTP response of 500 means "Internal server error", that is something has gone wrong, but the server can not be more specific about the error condition in its response to the client.  This is perceptually and actually the same as a standard GUI application suddenly crashing with only the operating system to report that it died.

The expected result in the general case is that the Output pane would contain some kind of graceful error message, at the very least, that the server didn't like what the user left in the Input field when hitting "Run", thus being explicit that there is something wrong with the user input, which may typically mean an HTTP 4xx response, rather than a 5xx which is saying its the server at fault.

For a null input a good response would likely be that the input is correct but is a null program.

In contrast to this, providing a valid input such as ```define "Number1": 1``` does provide a successful result.

**Comment by duncand** [comment]
On further investigation, this 500 error seems to occur in any case where the code does execute correctly, but it doesn't have any "define" to provide reflection output for.

```
library x version '1.0.0'
//define "Number1": 1
```

That example will produce a 500 error, but uncommenting the second line will reflect that define in the Output instead.

**Comment by c-schuler** [comment]
Thank you for reporting this error. 
The Runner should now be giving more descriptive errors for the cases you described as well as translation errors. This was resolved in a commit to the [Execution Service](https://github.com/DBCG/cql_execution_service/commit/22dcc3dce3a0149b148fb95ee95767ba55f7b3e1)

**Comment by duncand** [comment]
Thank you, I confirm that http://cql-runner.dataphoria.org is now producing meaningful output for any inputs that I threw at it, and nothing is obscured by a nondescript 500 error anymore.
