### ISSUE TITLE
web service gives Java cast error when selecting a List

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_runner#11]
For the web service http://cql-runner.dataphoria.org some "define" work and some don't.

Given this in the Input:

```
define "Number1": 1
define "bar": List<System.Integer>{5,6,2}
define "foo": Interval[5,6]
```

Hitting "Run" produces this output:

```
>> foo [3:1] Interval [ 5, 6 ]
>> Error: java.lang.Integer cannot be cast to org.hl7.fhir.instance.model.api.IBaseResource
>> Number1 [1:1] 1
```

Now the List example is exactly as in the CQL specification.  The CQL Runner is failing to handle it properly, while the Integer and Interval examples are working fine in the same run.

Another odd thing is that reflection of the values is in the opposite order that they were entered.

**Comment by c-schuler** [comment]
Resolved in a fix to the execution service:
https://github.com/DBCG/cql_execution_service/commit/a23bbdb53b58b4834f88ed131e66acff28aabb5d

Looks like the order gets messed up when there is an error in one of the expressions - not too worried about that.

**Comment by duncand** [comment]
Thank you, I confirm that this issue with http://cql-runner.dataphoria.org is fixed.
