### ISSUE TITLE
CQL Runner all Translation Error messages display in 1 long line

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_runner#12]
The CQL Runner at http://cql-runner.dataphoria.org displays runtime results nicely, one per line, but if a failure occurred early when translating the CQL to ELM, the whole list of errors, each with a line/col indicator, are all a single run-on sentence; they all display on one line.

This ticket is a request to display each Translation Error on a separate line so it can be read effectively.  It should be a simple matter of adding a line break in the Output before each item.

**Comment by c-schuler** [comment]
This issue was resolved in the [Execution Service](https://github.com/DBCG/cql_execution_service/commit/4e826f81f1be094b0c70d8939fd218640648d5ed)

**Comment by duncand** [comment]
Thank you, I confirm that http://cql-runner.dataphoria.org now displays each Translation Error of a list on its own line.

This might normally have been implemented differently, such that the comma-space being placed between list elements in the Output would instead be a comma-linebreak, where the actual fix added a line break after each list item itself and before the comma, however the existing fix does the job.
