### ISSUE TITLE
CQL Runner inexplicable list cardinality errors

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_runner#13]
With http://cql-runner.dataphoria.org enter the following simplest-case program for Input:

```
//library R
using FHIR
context Patient
define x: 1
```

Hitting the Run button will produce this output:

```
>> x [4:1] 1
>> Error: Expected a list with at most one element, but found a list with multiple elements.
```

Attempting to run many different programs produces either one or often many instances of the above Error message; there is no obvious direct cause and the errors seem to be originating from the internals of CQL Runner.

The above program is the simplest reproducing case.  Removing the "context Patient" makes the error go away.  Removing the "using FHIR" also makes the error go away.  Technically the "using" and "context" lines are the only ones required, and produce the error message alone.  The presence or absence of the "library" line has no effect.  (The "define" shows the program is otherwise running.)

Since presumably real program errors can result in the cardinality issue, the above errors can confuse as to whether someone's code is at fault or not.  Otherwise it is a lot of verbosity in the output.

Thank you in advance for a quick fix.

**Comment by c-schuler** [comment]
This issue was resolved in the [Execution Service](https://github.com/DBCG/cql_execution_service/commit/4e826f81f1be094b0c70d8939fd218640648d5ed)

**Comment by duncand** [comment]
Unfortunately this problem is not fixed in the general case.

Try running this program, and it spits out 3 instances of the "Expected a list..." error, one for each "define".

```
library X version '1.0.0'
using FHIR version '1.8'
include FHIRHelpers version '1.8' called FHIRHelpers
parameter "Measurement Period" Interval<DateTime>
context Patient
define "Is Female":
    Patient.gender = 'female'
define "Is Age 24 to 64":
    AgeInYearsAt(end of "Measurement Period") between 24 and 64
define "In Demographic":
  AgeInYearsAt(start of "Measurement Period") >= 13
define y: 1
```

I believe the above CQL is correct, if there in fact is a code problem here, please say so.  But if that's the case, then there's a problem in many documented examples, including the "gold standard" example https://github.com/esacinc/CQL-Formatting-and-Usage-Wiki/blob/master/Source/Example%20Measures/EXM137v5/EXM137v5_QDM.cql that the third line is copied from.

Your fix did suppress that error for the specific simplest-case program given first, but it turns out that it did not suppress at least some of the other instances of that error.

Either the general solution requires multiple code changes, or there is a single more general change that needs doing and you should start by reverting the one-liner that handled the "patient" specific fix.

**Comment by c-schuler** [comment]
This should be resolved now. 
Use the following snippet to test instead of the dstu2 version you posted above:
```
library X version '1.0.0'
using FHIR version '3.0.0'
parameter "Measurement Period" Interval<DateTime>
context Patient
define "Is Female":
    Patient.gender.value = 'female'
define "Is Age 24 to 64":
    AgeInYearsAt(end of "Measurement Period") between 24 and 64
define "In Demographic":
  AgeInYearsAt(start of "Measurement Period") >= 13
define y: 1
```

**Comment by duncand** [comment]
Thank you, I confirm that http://cql-runner.dataphoria.org no longer exhibits this problem, including with a full library.
