### ISSUE TITLE
CQL Runner fails with FHIR version 3

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_runner#14]
The current CQL Runner service at http://cql-runner.dataphoria.org fails to handle FHIR version 3 in a variety of different ways.

Running the following code example as is will output the define without errors:

```
library Y version '1.0.0'
//using FHIR version '3.0.1'
//using FHIR version '3.0.0'
using FHIR version '1.8'
include FHIRHelpers
define x: 1
```

Trying to use FHIR 3.0.1 (the latest version) instead and without any FHIRHelpers produces the error:

```
>> Translation Error: [Y-1.0.0[3:1, 3:26]Could not resolve model info provider for model FHIR, version 3.0.1.]
```

Trying to use FHIR 3.0.0 instead and without any FHIRHelpers doesn't have an error.

Trying to use FHIR 3.0.0 but with FHIRHelpers produces a ream of errors from inside the FHIRHelpers used implicitly by CQL Runner.

```
>> Translation Error: [FHIRHelpers-1.8[3:1, 3:24]Could not load model information for model FHIR, version 1.8 because version 3.0.0 is already loaded.
, FHIRHelpers-1.8[5:35, 5:45]Could not resolve model name FHIR
, FHIRHelpers-1.8[5:1, 6:54]org.hl7.elm.r1.Null cannot be cast to org.hl7.elm.r1.TypeSpecifier
, FHIRHelpers-1.8[8:37, 8:49]Could not resolve model name FHIR
, FHIRHelpers-1.8[8:1, 9:78]org.hl7.elm.r1.Null cannot be cast to org.hl7.elm.r1.TypeSpecifier
...
```

More generally, FHIRHelpers internally requires FHIR 1.8 and so any library using FHIRHelpers can't use any other FHIR version.

The task of this ticket is to make CQL Runner accept FHIR 3.0.1 or otherwise at least make it so FHIRHelpers works with FHIR 3.0.0 or the latest FHIR version that is supported at the time.

**Comment by c-schuler** [comment]
I added all the versions of FHIRHelpers and changed the way they are resolved. 
All the following should work:
```
using FHIR version '1.0.2'
include FHIRHelpers version '1.0.2' called FHIRHelpers
```
```
using FHIR version '1.6'
include FHIRHelpers version '1.6' called FHIRHelpers
```
```
using FHIR version '1.8'
include FHIRHelpers version '1.8' called FHIRHelpers
```
```
using FHIR version '3.0.0'
include FHIRHelpers version '3.0.0' called FHIRHelpers
```

**Comment by duncand** [comment]
Thank you.  I confirm that http://cql-runner.dataphoria.org now runs with the combination of FHIR 3 and FHIRHelpers.
