### ISSUE TITLE
HTTP 400 errors for Coverage resource

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_runner#15]
The CQL Runner at http://cql-runner.dataphoria.org has a problem with the Coverage FHIR resource.

```
library L version '1.0.0'
using FHIR version '3.0.0'
//context Patient
define x: [Coverage] Cov
```

Execute that and you get this result:

```
>> Error: HTTP 400 Bad Request: Unknown search parameter "patient". Value search parameters for this search are: [_id, _language, beneficiary, class, dependent, group, identifier, payor, plan, policy-holder, sequence, subclass, subgroup, subplan, subscriber, type]
```

Under normal usage (and with context Patient uncommented), that 400 error may appear multiple times, such as once for each define that mentions [Coverage] directly or indirectly.

**Comment by duncand** [comment]
As an update, using "context Population" instead causes this to produce a result instead of erring.  I don't know if that means [Coverage] always needs to be invoked in Population context, or if there is some other problem going on here.

**Comment by c-schuler** [comment]
This was an issue in the cql_engine. The patient search parameter differs from resource to resource. Usually it is either "subject" or "patient", but with coverage it is "beneficiary". I added that and it should be working as expected now.

**Comment by duncand** [comment]
Thank you, I confirm that http://cql-runner.dataphoria.org no longer has the problem.
