### ISSUE TITLE
Interval math logical inconsistency between collapse() and union()

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_runner#16]
The CQL Runner at http://cql-runner.dataphoria.org produces logically inconsistent results for similar operations on intervals of integers, and possibly other discrete types.

Run the following code:

```
define dc1: collapse { Interval[4.0,6.0], Interval[6.0,8.0] }
define du1: Interval[4.0,6.0] union Interval[6.0,8.0]
define ic1: collapse { Interval[4,6], Interval[6,8] }
define iu1: Interval[4,6] union Interval[6,8]
define dc2: collapse { Interval[4.0,6.0], Interval[7.0,8.0] }
define du2: Interval[4.0,6.0] union Interval[7.0,8.0]
define ic2: collapse { Interval[4,6], Interval[7,8] }
define iu2: Interval[4,6] union Interval[7,8]
```

These are the results:

```
>> dc1 [1:1] [Interval [ 4.0, 8.0 ]]
>> du1 [2:1] Interval [ 4.0, 8.0 ]
>> ic1 [3:1] [Interval [ 4, 8 ]]
>> iu1 [4:1] Interval [ 4, 8 ]
>> dc2 [5:1] [Interval [ 4.0, 6.0 ], Interval [ 7.0, 8.0 ]]
>> du2 [6:1] Null
>> ic2 [7:1] [Interval [ 4, 6 ], Interval [ 7, 8 ]]
>> iu2 [8:1] Interval [ 4, 8 ]
```

Now the problem is with the last 2 lines, which logically should produce equivalent results like all 3 of the previous pairs but don't.

The integer type is such that every value has a defined predecessor and successor value, which means that 2 intervals of integer can be known to touch if their endpoints are adjacent, even if they aren't equal.  

Now it is actually a design decision as to whether interval logic should specially recognize discrete types like integers and treat distinct closed endpoints as touching, or decide not to if it wants a measure of consistency with continuous types like general rationals.  But whatever decision is made, it needs to be followed consistently, and the last 2 lines show that isn't the case.

So either ic2 needs to produce a single Interval[4,8] or iu2 needs to return Null.

**Comment by duncand** [comment]
Note: I would expect that the CQL specification should say which behaviour should be taken rather than it being implementation-defined, but I didn't see anywhere that it did.  So this issue may also indicate a CQL (or ELM) specification deficiency.

**Comment by c-schuler** [comment]
This is a bug that was resolved in a [commit](https://github.com/DBCG/cql_engine/commit/e20ade7ebdd01965918766d8822d181f5ce4670e) the engine. 

With the new logic, the result of ic2 would be Interval[4,8].

I agree that the spec should be clarified regarding this operator.

**Comment by duncand** [comment]
I confirm that http://cql-runner.dataphoria.org shows fixed/consistent behaviour, thank you.
