### ISSUE TITLE
CQL Formatter is down at http://cql-runner.dataphoria.org/

### ISSUE THREAD

**Issue by jduke99** [DBCG/cql_runner#25]
The formatter page is blank. CQL runner working fine.

Running Chrome.

**Comment by brynrhodes** [comment]
Hi @jduke99 , thank you for the report. It looks like that's a stale link. At some point, we changed it from a separate page to a button on the main page. Using that button works for me in Firefox and Chrome. I've updated the readme to reflect that change, can you give it a whirl and let me know if you have any issues?
