### ISSUE TITLE
Component integration.

### ISSUE THREAD

**Issue by preston** [DBCG/cql_runner#4]
This looks great, and I'd like to try integrating it into the knowledge artifact editor at http://knartwork.healthcreek.org, which is an Angular 2 application.  Do you have guidance on how to this is modularized/componentized such that it can be included into other apps, and how to bind input/output to client-side data models?

**Comment by preston** [comment]
Hello? :)

**Comment by c-schuler** [comment]
Apologies for the delay Preston. I have taken this issue under advisement...

**Comment by c-schuler** [comment]
I have published a cql-runner package with npm:
https://www.npmjs.com/package/cql-runner
Follow the readme for instructions on how to implement.

**Comment by preston** [comment]
Looks awesome -- much looking forward to trying it out! Thanks!
