### ISSUE TITLE
Breaking compile-time .ts error on module inclusion.

### ISSUE THREAD

**Issue by preston** [DBCG/cql_runner#5]
When following the component usage instructions, it looks like there's an issue with the packaged TypeScript declarations. For example:

> ERROR in ./~/cql-runner/index.ts
Module build failed: Error: Typescript emitted no output for /Users/preston/Developer/git/knartwork/node_modules/cql-runner/index.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
  at Object.loader (/Users/preston/Developer/git/knartwork/node_modules/ts-loader/dist/index.js:33:15)
 @ ./src/app.module.ts 14:19-40
Warning: Task "webpack:build" failed. Use --force to continue.
Aborted due to warnings.

**Comment by c-schuler** [comment]
Published new version with npm using outDir + .d.ts + .js method. Also eliminated the previous styling requirements.

**Comment by preston** [comment]
v1.0.2 unfortunately still breaks:

> WARNING in ./~/cql-runner/index.js
Cannot find SourceMap 'index.js.map': Error: Cannot resolve 'file' or 'directory' ./index.js.map in /Users/preston/Developer/git/knartwork/node_modules/cql-runner

> ERROR in ./~/cql-runner/cql-runner-wrapper.component.ts
(8,13): error TS2304: Cannot find name 'module'.

> ERROR in ./~/cql-runner/cql-runner-wrapper.module.ts
Module build failed: Error: Typescript emitted no output for /Users/preston/Developer/git/knartwork/node_modules/cql-runner/cql-runner-wrapper.module.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
  at Object.loader (/Users/preston/Developer/git/knartwork/node_modules/ts-loader/dist/index.js:33:15)
 @ ./~/cql-runner/index.js 5:9-47

> ERROR in ./~/cql-runner/cql-runner-wrapper.component.ts
Module build failed: Error: Typescript emitted no output for /Users/preston/Developer/git/knartwork/node_modules/cql-runner/cql-runner-wrapper.component.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
  at Object.loader (/Users/preston/Developer/git/knartwork/node_modules/ts-loader/dist/index.js:33:15)
 @ ./~/cql-runner/index.js 6:9-50
Warning: Task "webpack:build" failed. Use --force to continue.

> Aborted due to warnings.

**Comment by c-schuler** [comment]
Pushed version 1.0.9 to npm. Used different method with more stringent testing. Let me know how it goes.

**Comment by preston** [comment]
Still broken, unfortunately. With v1.0.9:

    ERROR in ./src/app.module.ts
    (7,10): error TS2305: Module '"/Users/preston/Developer/git/knartwork/node_modules/cql-runner/index"' has no exported member 'CqlRunnerModule'.

    ERROR in /Users/preston/Developer/git/knartwork/tsconfig.json
    error TS6059: File '/Users/preston/Developer/git/knartwork/node_modules/ng2-ace-editor/src/component.ts' is not under 'rootDir' '/Users/preston/Developer/git/knartwork/src'. 'rootDir' is expected to contain all source files.

    ERROR in /Users/preston/Developer/git/knartwork/tsconfig.json
    error TS6059: File '/Users/preston/Developer/git/knartwork/node_modules/ng2-ace-editor/src/directive.ts' is not under 'rootDir' '/Users/preston/Developer/git/knartwork/src'. 'rootDir' is expected to contain all source files.

    ERROR in /Users/preston/Developer/git/knartwork/tsconfig.json
    error TS6059: File '/Users/preston/Developer/git/knartwork/node_modules/ng2-ace-editor/src/module.ts' is not under 'rootDir' '/Users/preston/Developer/git/knartwork/src'. 'rootDir' is expected to contain all source files.
    Warning: Task "webpack:build" failed. Use --force to continue.

    Aborted due to warnings.

If you need a downstream project to help test, I've gone ahead and intentionally committed the broken Knartwork integration over in that repo, if that helps: https://github.com/cqframework/knartwork

**Comment by c-schuler** [comment]
Please follow the instructions here:
https://www.npmjs.com/package/cql-runner

Note that CqlRunnerModule is now just RunnerModule

**Comment by c-schuler** [comment]
I have gotten past those errors.

The first error is resolved by renaming the CqlRunnerModule to RunnerModule and also listing the ApiService as a provider in the base module.

The next three can be resolved with a change to the tsconfig:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "outDir": "build"
    },
    "compileOnSave": false,
    "include": [
        "src/**/*",
        "node_modules/ng2-ace-editor/**/*",
        "node_modules/cql-ace-syntax/*"
    ],
    "exclude": [
        "node_modules",
        "bower_components",
        "typings/globals",
        "typings/index.d.ts"
    ],
    "filesGlob": [
        "src/**/*.ts"
    ]
}
``` 
Furthermore, in the applicaton.pug file, add this script before the main.bundle.js script:
`script(src="ace.js")`

Now append the following to the "copy" Grunt task:
```
{
   cwd: 'node_modules/cql-ace-syntax/',
   src: "ace.js",
   dest: 'build/',
   expand: true
}
```
That should get you up and running. I have verified that this solution works with the knartwork project.

**Comment by c-schuler** [comment]
Issued pull request with solution here:
https://github.com/cqframework/knartwork/pull/4

Will leave this issue open until I get your feedback.

**Comment by preston** [comment]
@c-schuler Thanks for the update! I'm hoping to look at this soon .. just been on work travel this week.

**Comment by preston** [comment]
@c-schuler Getting very close ... everything does seem to be building again and other updates for the Angular 4 release have been included. When adding a cql-runner component, I'm getting:

```
vendor.bundle.js:1450 ERROR ReferenceError: CodeMirror is not defined
    at new RunnerComponent (main.bundle.js:5806)
    at createClass (vendor.bundle.js:11258)
    at createDirectiveInstance (vendor.bundle.js:11089)
```

I'm not sure where CodeMirror is supposed to be defined.

**Comment by c-schuler** [comment]
I am working on an NPM module with CodeMirror, but there is not a functional release yet...

Please use the cql-runner 1.0.9 npm package.

**Comment by preston** [comment]
Seems to be happier with v1.0.9. I would suggest yanking the broken ones if possible before anyone tries them.
