### ISSUE TITLE
Date values are displayed with class name

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_runner#6]
This expression:

define Date1: @2012-03-10

Gives this result:

Date1 [1:5] org.opencds.cqf.cql.runtime.DateTime@7ff7c68f

It should give the ISO 8601 string representation of the date/time value.

**Comment by c-schuler** [comment]
Resolved: https://github.com/DBCG/cql_engine/commit/bbbcccfd3893222d7fe871b216adf48178c82441#diff-4fca5d573a0ad4cc02c43fcd75d6989d

All built-in types will now be displayed in a descriptive manner.
